---
# Pour exécuter via ansible
#     ansible-playbook -i hosts 04-playbook-variable.yml

- name: Syntaxe utiliser des variables
  hosts: 127.0.0.1
  connection: local
  vars:
    ma_premiere_variable: "Le contenu de ma variable !"

  tasks:
    - debug:
        msg: '{{ ma_premiere_variable }}'
    
    - debug:
        msg: 'Un autre petit message dans lequel la variable {{ ma_premiere_variable }} est affichée'

    - debug:
        msg: Pas besoin de guillemets si aucune variable n'est utilisée
...
